# Generated by Django 5.2.13 on 2026-04-28 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_code', models.TextField()),
                ('language', models.CharField(default='cpp', max_length=10)),
                ('source', models.CharField(default='web_upload', max_length=50)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('prediction', models.CharField(blank=True, default='', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bronze Submission',
                'verbose_name_plural': 'Bronze Submissions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
