# Generated by Django 5.2.13 on 2026-05-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzesubmission',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='BatchSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Batch name or folder name', max_length=255)),
                ('total_files', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Session',
                'verbose_name_plural': 'Batch Sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='bronzesubmission',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.batchsession'),
        ),
    ]
