# inventory/hosts.yml
all:
  hosts:
    gpu-server:
      ansible_host: 127.0.0.1 # Change to your server IP
      ansible_user: root
      gpu_driver_version: "535"
      microk8s_channel: "1.28/stable"
